gobiglatest/app/Http/routes.php
<?php

Route::group(['middleware' => ['web','Checkdomain']], function () {

	// for Home
	Route::get('/', [
		'uses' => 'HomeController@index', 
		'as' => 'home'
	]);
        
        Route::group(['prefix' => 'paypal'], function () {	
            
        // for process
	Route::get('/', [
		'uses' => 'PaypalController@process', 
		'as' => 'processpaypal'
	]);
        
        Route::post('/success', [
		'uses' => 'PaypalController@success', 
		'as' => 'sucesspaypal'
	]);
        
        Route::post('/cancel', [
		'uses' => 'PaypalController@cancel', 
		'as' => 'cancelpaypal'
	]);
        
        
        });

	//for themes demo
	Route::get('/theme/{theme_id}', 'HomeController@selecttheme');
	Route::get('/theme/sell-home/{theme_id}', 'HomeController@showsellhome');
	Route::get('/theme/cash-offer/{theme_id}', 'HomeController@showcashoffer');
	Route::get('/theme/questions/{theme_id}', 'HomeController@showquestions');
	Route::get('/theme/how-it-works/{theme_id}', 'HomeController@showhowitworks');
	Route::get('/theme/testimonials/{theme_id}', 'HomeController@showtestimonial');
	Route::get('/theme/about-us/{theme_id}', 'HomeController@showaboutus');
   
	
	Route::get('/try-it-free', 
	[
		'uses' => 'HomeController@get_tryitfree',
		'middleware' => 'Checkdomain'
	]);
	Route::get('/about-us', 'HomeController@get_aboutus');
	Route::get('/how-it-works', 'HomeController@get_howitworks');
	Route::get('/pricing', 'HomeController@get_pricing');
	Route::get('/get-website-free', 'HomeController@get_website_free');
	Route::get('/testimonials', 'HomeController@get_testimonials');
	Route::get('/contact-us', 'HomeController@get_contactus');
	Route::post('/add-contactus', 'HomeController@add_contactus');
	Route::get('/affiliate-program', 'HomeController@get_affiliateprogram');
	Route::get('/affiliate-term', 'HomeController@get_affiliateterm');
	Route::get('/privacy-policy', 'HomeController@get_privacypolicy');
	Route::get('/faq', 'HomeController@get_faq');
	Route::post('/add-visitor', 'VisitorsController@addvisitor');
	Route::get('/add-visitor/thankyou', 'VisitorsController@showthankyou');
	// Admin
	Route::get('admin', [
		'uses' => 'AdminController@admin',
		'as' => 'admin',
		'middleware' => 'admin'
	]);

	Route::get('medias', [
		'uses' => 'AdminController@filemanager',
		'as' => 'medias',
		'middleware' => 'redac'
	]);


	//for front user...
	Route::group(['middleware' => ['user']], function ()
	{
		Route::get('/cancel-subscription/{user_id}', 'AgentController@cancelSubscription');
		Route::get('/cancel-subscription/', 'AgentController@cancelSubscription');
		Route::get('/dashboard/{user_id}', 'AgentController@showdashboard');
		Route::get('/account/{user_id}', 'AgentController@showaccount');
		Route::get('/change-password/{user_id}', 'AgentController@changepassword');
		Route::get('/content/{user_id}', 'AgentController@showcontent');
		Route::get('/visitors/{user_id}', 'AgentController@showvisitors');
		Route::post('/addcontent', 'AgentController@addcontent');
		Route::post('/notes', 'AgentController@addnotes');
		Route::get('/referal-url/{user_id}', 'AgentController@showurl');
		Route::get('/affiliates/{user_id}', 'AgentController@showaffiliates');
		Route::post('/adddomainname', 'AgentController@add_domainname');
		Route::match(['get', 'post'], '/getpackages/{user_id}', 'AgentController@getpackages');
		Route::match(['get', 'post'], '/getmember-payment/{user_id}/{pid}/{amount}', 'AgentController@getmemberpackage');
		Route::post('/editprofile', 'AgentController@editagentprofile');
		Route::post('/editpassword', 'AgentController@editagentpassword');
		Route::get('/remove_agent_domain/{agentid}', 'AgentController@remove_domain');
		Route::get('/banners/{user_id}', 'AgentController@showbanner');
		Route::get('/remove_content_logo/{agentid}', 'AgentController@remove_contentlogo');
	});

	//To check domain available or not
	/*Route::group(['middleware' => ['Checkdomain']], function ()
	{
		Route::get('errors/404', 'HomeController@get_tryitfree');
	
	
	}*/
	
	Route::group(['middleware' => ['admin']], function ()
	{
	// for show User in admin...
	Route::get('user/sort/{role}', 'UserController@indexSort');

	Route::get('user/roles', 'UserController@getRoles');
	Route::post('user/roles', 'UserController@postRoles');

	Route::put('userseen/{user}', 'UserController@updateSeen');

	Route::resource('user', 'UserController');

	// Package in admin
	Route::resource('package', 'PackageController');
	Route::get('/uploadpdf', 'PackageController@uploadpdf');
	Route::post('/upload', 'PackageController@uploadfile');
	Route::post('/editpackage', 'PackageController@updatePackage');
    // for service package
	Route::resource('servicepackage', 'ServicePackageController');
	//Route::get('/servicepackage', 'ServicePackageController@getservicepackage');
	Route::post('/editservicepackage', 'ServicePackageController@updatePackage');
	
	// Affiliation Management of admin
	//Route::get('/affiliation', 'AffiliationController@index');
	Route::get('/affiliation', 'AffiliationController@getcommission'); 
	Route::get('/showaddfee', 'AffiliationController@showfees');
	Route::get('/referalfee', 'AffiliationController@showrefview');
	Route::get('/editreferalfee/{fee_id}', 'AffiliationController@editrefview');
	Route::post('/editfees', 'AffiliationController@editreffees');
	Route::post('/addfees', 'AffiliationController@setfees');
	Route::get('/deletereferalfee/{fees_id}', 'AffiliationController@deletefees');
	Route::get('/show-visitors', 'VisitorsController@index');
	Route::get('/email-campaign', 'VisitorsController@showemailcampaign');
	Route::get('/edit-emailsetup/{c_id}', 'VisitorsController@editemailcampaign');
	Route::get('/setup-email', 'VisitorsController@setupemail');
	Route::post('/addemailcontent', 'VisitorsController@addemailcontent');
	Route::post('/editemailcontent', 'VisitorsController@editemailcontent');
	Route::get('/delete-emailsetup/{co_id}', 'VisitorsController@delete_emailcontent');
	Route::get('/test-emailsetup/{temp_id}', 'VisitorsController@testemailsetup');
	Route::post('/sendtestmail', 'VisitorsController@sendtestmail');
	Route::post('/change-status', 'AffiliationController@change_paidstatus');
	//Route::get('/partner-order', 'OrderController@showpartnerorder');
	Route::get('/member-order', 'OrderController@showpartnerorder');
	Route::any('/admin/search/order', 'OrderController@searchorder');
	Route::any('/admin/search/affiliation', 'AffiliationController@searchaffiliation');
	Route::any('/admin/search/visitors', 'VisitorsController@searchvisitors');
	Route::any('/admin/search/users', 'UserController@searchusers');
	Route::get('/show-queries', 'OrderController@show_contact_queries');
	Route::any('/admin/search/contactquery', 'OrderController@search_contact_query');
	Route::get('/reply-queries/{id}', 'OrderController@reply_contact_query');
	Route::post('/sendreply', 'OrderController@send_reply');
	Route::get('/admin/download-orders/', 'OrderController@download_orders');
	Route::get('/admin/download-users/', 'UserController@download_users');
	Route::get('/admin/download-affiliates/', 'AffiliationController@download_affiliates');
	Route::get('/admin/download-visitors/', 'VisitorsController@download_visitors');
	Route::get('/admin/remove_content_logo/{agentid}', 'AgentController@remove_contentlogo');
	Route::get('/admin/cancel-subscription/{agentid}', 'AgentController@cancelSubscription');
        Route::get('/admin/profile', 'AdminController@getprofile');
	Route::post('/admin/editprofile', 'AdminController@editprofile');
	Route::get('/admin/change-password', 'AdminController@changepassword');
	Route::post('/admin/editpassword', 'AdminController@editpassword');
	Route::get('/service-referal-fee', 'ServicePackageController@showrefview');
	Route::get('/showaddservicefee', 'ServicePackageController@showfees');
	Route::post('/addservicefees', 'ServicePackageController@setfees');
	Route::get('/edit-service-referalfee/{fee_id}', 'ServicePackageController@editrefview');
	Route::post('/edit-service-fees', 'ServicePackageController@editreffees');
	Route::get('/delete-service-referalfee/{fees_id}', 'ServicePackageController@deletefees');
    });
	// Authentication routes...
	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');
	Route::get('confirm/{token}/{id}', 'AgentController@getConfirm');

	// Resend routes...
	Route::get('auth/resend/{user_id}', 'AgentController@getResend');

	// Registration routes...
	Route::get('auth/register', 'Auth\AuthController@getthemes');
	Route::match(['get', 'post'], 'auth/getregister', 'Auth\AuthController@getregister');
	Route::match(['get', 'post'], 'auth/get-member-register/{pid}/{amount}', 'Auth\AuthController@getmemberregister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');
	Route::post('auth/checkemail', 'Auth\AuthController@checkemail');
	Route::post('auth/checkdomain', 'Auth\AuthController@checkdomain');
	Route::post('auth/payment', 'Auth\AuthController@addpayment');
	// Password reset link request routes...
	Route::get('password/email', 'Auth\PasswordController@getEmail');
	Route::post('password/email', 'Auth\PasswordController@postEmail');
	// Password reset routes...
	Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
	Route::post('password/reset', 'Auth\PasswordController@postReset');
	Route::get('/referral/{user_id}', 'AgentController@countaffiliates');
	
});

gobiglatest/app/Http/Controllers/AffiliationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Affiliation;

use App\Models\Referalfees; 
use App\Models\Referalpayment;
use Illuminate\Support\Facades\Redirect;

use Illuminate\Support\Facades\Validator;
use DB;
class AffiliationController extends Controller
{
    public function index()
    {
        $aff_data = new Affiliation;
        $aff_results = $aff_data->getalldata();
        if(count($aff_results))
        {
            for($i=0; $i<count($aff_results); $i++)
            {
                $aff_results[$i]->agentname = DB::table('users')->where('id', $aff_results[$i]->agent_id)->value('username');
            }
            $results = $aff_results;
        }
        else
        {
            $results = '';
        }
    	return view('back.affiliation.index', compact('results'));
    }
	
	public function getcommission()
    {
        $aff_data = new Referalpayment;
        $aff_results = $aff_data->getdata();
		
        if(count($aff_results))
        {
            for($i=0; $i<count($aff_results); $i++)
            {
                $aff_results[$i]->agentname = DB::table('users')->where('id', $aff_results[$i]->agent_id)->value('username');
            }
            $results = $aff_results;
        }
        else
        {
            $results = '';
        }
    	return view('back.affiliation.index', compact('results'));
    }
	
	
	
    public function showfees()
    {
    	return view('back.affiliation.addreferalfee');
    }
    public function setfees(Request $request)
    {
    	$data['type'] = $request->input('type');
    	$data['monthly_bonus'] = $request->input('monthly_bonus');
        $data['annual_bonus'] = $request->input('annual_bonus');
    	$rule  =  array(
                   			'type'       => 'required',
                    		'monthly_bonus'      =>  array('required', 'regex:/^[0-9]*$/'),
                            'annual_bonus' => array('required', 'regex:/^[0-9]*$/')
                		);
		$validator = Validator::make($data,$rule);
		if ($validator->fails())
        {
            return redirect()->back()->withErrors($validator->messages());
        }
        else
        {
            $rfee = new Referalfees;
			$rfee->savefeeData($data);
			return Redirect::to('/referalfee')->withMessage('Commission inserted successfully.');      
        }
    }
    public function showrefview()
    {
    	$allfees = new Referalfees;
        $result = $allfees->getallfees();
        if(!empty($result))
        {
            $fees = $result;
        }
        else
        {
            $fees = '';
        }
    	return view('back.affiliation.referalfee', compact('fees'));
    }

    public function editrefview($feeid)
    {
        $editfees = new Referalfees;
        $fees = $editfees->getfeesbyid($feeid);
        return view('back.affiliation.editreferalfee', compact('fees'));
    }

    public function editreffees(Request $request)
    {
        $data['feeid'] = $request->input('feeid');
        $data['type'] = $request->input('type');
        $data['monthly_bonus'] = $request->input('monthly_bonus');
        $data['annual_bonus'] = $request->input('annual_bonus');
        $rule  =  array(
                            'type'       => 'required',
                            'monthly_bonus'      =>  array('required', 'regex:/^[0-9]*$/'),
                            'annual_bonus' => array('required', 'regex:/^[0-9]*$/')
                        );
        $validator = Validator::make($data,$rule);
        if ($validator->fails())
        {
            return redirect()->back()->withErrors($validator->messages());
        }
        else
        {
            $updated_fee = new Referalfees;
            $updated_fee->updatefeeData($data);
            return Redirect::to('/referalfee')->withMessage('Commission updated successfully.');      
        }
    }

    public function deletefees($feesid)
    {
        $deletefees = new Referalfees;
        $deletefees->delete_fees($feesid);
        return Redirect::to('/referalfee')->withMessage('Commission deleted successfully.');
    }

    public function change_paidstatus(Request $request)
    {
        $data['agent_id'] = $request->input('id');
        $status = new Referalpayment;
        $result = $status->change_payment_status($data);
        $aff = new Affiliation;
        $status_result = $aff->updatedata($data);
        if($status_result > 0)
        {
            $alldata = $aff->get_affiliates_by_id($data['agent_id']);
            return $alldata;
        }
        else
        {
            return $status_result;
        }
    }

    public function searchaffiliation(Request $request)
    {
        $search = $request->SearchText;
        $record_no = $request->records_no;
        $main_query = Affiliation::select('affiliation.*', 'users.username as agentname','users.id')                   
                    ->join('users', 'users.id', '=', 'affiliation.agent_id')->orderBy('affiliation.id', 'desc');
                   
        if($search != '' || $search != null)
        {
            $main_query->where(function ($query) use ($search) {
                    $query->where('users.username', 'like', '%'.$search.'%');
                    });
        }
        if($record_no != '' || $record_no != null)
        {
            $results = $main_query->paginate($record_no);
        }
        else
        {
            $results = $main_query->paginate(10);
        }
         if($request->ajax())
         {
            $data = [];
            $data['status'] = 'success';
            $data['html'] = \View::make('back.affiliation.part')->withResults($results)->render();
            $data['count'] = count($results);
         }
         else
         {
            return view('back.affiliation.index', compact('results'));
         }

        return response()->json($data);
    }

    public function download_affiliates(Request $request)
    {
        $agent_name = $request->SearchText;
        $main_query = Affiliation::select('affiliation.*','users.id','users.username as agentname')
                    ->join('users','affiliation.agent_id','=','users.id')->orderBy('affiliation.id', 'desc')->where('users.id','!=','');
        if($agent_name != '' || $agent_name != null)
        {
            $main_query->where(function ($query) use ($agent_name) {
                    $query->where('users.username', 'like', '%'.$agent_name.'%');
                    });
        }
        $affiliates = $main_query->get();
        $filename = 'affiliates-'.time().'.csv';
        $handle = fopen($filename, 'w+');
        fputcsv($handle, array('Agentname', 'Total Cicks', 'Total Signup', 'Total Payment', 'Total Earning', 'Payment Due'));
        foreach ($affiliates as $row) 
        {
            fputcsv($handle, array($row->agentname, $row->total_clicks, $row->total_signup, $row->total_payment, $row->total_earning, $row->payment_due));
        }
        fclose($handle);

            $headers = array(
                        'Content-Type' => 'text/csv',
                    );

            return \Response::download($filename, $filename, $headers)->deleteFileAfterSend(true);
    }
}

gobiglatest/resources/views/back/affiliation/addreferalfee.blade.php
@extends('back.template')
@section('head')
	<style type="text/css">
		.table { margin-bottom: 0; }
		.panel-heading { padding: 0 15px; }
	</style>
@stop
@section('main')
	<h1 class="page-header">Set Commission</h1>
	<div class="col-sm-12">
		@if (Session::has('message'))
    		<div class="alert alert-success">{{ Session::get('message') }}</div>
		@endif
		{!! Form::open(['url' => '/addfees', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}
		<label>Type</label>
		<select name="type" class="form-control">
			<option name="fixed" value="Fixed">Fixed</option>
		</select>
		@if ($errors->has('type'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('type') }}</div>
        @endif
		<br>
		<label>Monthly Commission</label>	
		<input type="text" name="monthly_bonus" class="form-control">
		@if ($errors->has('monthly_bonus'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('monthly_bonus') }}</div>
        @endif
        <br>
		<label>Annual Commission</label>	
		<input type="text" name="annual_bonus" class="form-control">
		@if ($errors->has('annual_bonus'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('annual_bonus') }}</div>
        @endif
        <a href="{!! url('/referalfee') !!}" class="k-cancel">Cancel</a>
		<input type="submit" name="add" value="Add" class="k-submit">	
		{!! Form::close() !!}
	</div>
@stop

gobiglatest/resources/views/back/affiliation/editreferalfee.blade.php
@extends('back.template')
@section('head')
	<style type="text/css">
		.table { margin-bottom: 0; }
		.panel-heading { padding: 0 15px; }
	</style>
@stop
@section('main')
	<h3 class="page-header">Set Commission</h3>
	<div class="row">
	<div class="col-sm-12">
		@if (Session::has('message'))
    		<div class="alert alert-success">{{ Session::get('message') }}</div>
		@endif
		{!! Form::open(['url' => '/editfees', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}
		<input type="hidden" name="feeid" value="{{ $fees[0]->id }}">
		<label>Type</label>
		<select name="type" class="form-control">
			<option name="fixed" value="Fixed" <?php if($fees[0]->type=="Fixed") echo 'selected="selected"'; ?>>Fixed</option>
		</select>
		@if ($errors->has('type'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('type') }}</div>
        @endif
		<br>
		<label>Monthly Commission</label>	
		<input type="text" name="monthly_bonus" class="form-control" value="{{ $fees[0]->monthly_bonus }}">
		@if ($errors->has('monthly_bonus'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('monthly_bonus') }}</div>
        @endif
        <br>
		<label>Annual Commission</label>	
		<input type="text" name="annual_bonus" class="form-control" value="{{ $fees[0]->annual_bonus }}">
		@if ($errors->has('annual_bonus'))
            <div class="alert alert-danger" role="alert">{{ $errors->first('annual_bonus') }}</div>
        @endif
		<a href="{!! url('/referalfee') !!}" class="k-cancel">Cancel</a>
		<input type="submit" name="save" value="Save" class="k-submit">	
		
		{!! Form::close() !!}
	</div>
	</div>
@stop

gobiglatest/resources/views/back/affiliation/index.blade.php
@extends('back.template')
@section('head')
	<style type="text/css">
		.table { margin-bottom: 0; }
		.panel-heading { padding: 0 15px; }
	</style>
<meta name="csrf-token" content="{{ csrf_token() }}" />
@stop
@section('main')
	{!! Form::open(['class' => ' form-horizontal', 'method' => 'post']) !!}
{!! csrf_field() !!}
<div class="form-group search-form-k">
<div class="col-md-3 col-sm-5">
	{!! Form::text('agentname', null, [
            'class'                         => 'form-control',
            'id'                            => 'agent_name',
            'placeholder'                   => 'Member name'
        ]) !!}
</div>
<div class="col-md-3 col-sm-5">
<a class="btn btn-primary" id="search_affiliation">Search</a>
</div>
</div>
<h1 class="page-header row no-margin"><span class="orders">Affiliation</span>
<div class="col-md-2 col-sm-5 pull-right">
<label class="fs-15">Records per page</label>
<select name="records" id="records" class="form-control" onchange="doAjaxSearchAffiliation()">
	<option value="10">10</option>
	<option value="20">20</option>
	<option value="30">30</option>
</select>
</div></h1>
{!! Form::close() !!}
<p class="text-right pcsv"><a href="#" onclick="save_affiliates()" class="csv-btn"><span> Export as <img src="{{ asset('images/csv-icon.png') }}"></span></a></p>
	<div id="statuschange" class="alert alert-success" style="display:none;">Payment status updated successfully.</div>
	<div id="alreadypaid" class="alert alert-danger" style="display:none;">Already Paid.</div>
		<div class="panel" id="resultContainer">
			@include('back.affiliation.part')
		</div>
@stop
@section('scripts')
<script>
function changestatus(id)
{
	$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
// Returns successful data submission message when the entered information is stored in database.
$.post("/change-status", {
id: id,
amount:100
}, function(data) {
	//console.log(data[0].total_earning);
	if(data != 0)
	{
		$('#alreadypaid').hide();
		$('#statuschange').show();
		$('#tearn'+id).html(data[0].total_earning);
		$('#tdue'+id).html(data[0].payment_due);
		$('#status'+id).html('Paid');
	}
	else
	{
		$('#statuschange').hide();
		$('#alreadypaid').show();
	}
});
}

$('#search_affiliation').on('click',function()
 	{
        doAjaxSearchAffiliation();
				 
    });
$('#agent_name').keydown(function (e){
    if(e.keyCode == 13){
        doAjaxSearchAffiliation();
    }
});
    function doAjaxSearchAffiliation()
	{
		var record = $('#records').val();
		var agentname = $('#agent_name').val();
			var dataString  = {SearchText:agentname,records_no:record};
			$.ajax({                       
			   url :  "/admin/search/affiliation",
			   type: "GET",
			   dataType: 'JSON',
			   data : dataString, 
			   cache:false,
			   success : function(data){
				   //console.log(data);
				   //alert(data.count);
				   if(data.count > 0)
				   {
				   		$('#resultContainer').html(data.html);
				   }
				   else
				   {
				   	 $('#resultContainer').html('No records found');
				   }
				 
			   }               
		   });
	}
	function save_affiliates()
	{
		doAjaxSearchAffiliation();
		var agentname = $('#agent_name').val();
		var dataString = {SearchText:agentname};
		window.location.href = '{!! url('/admin/download-affiliates/') !!}' + "?" + serialize(dataString);
	}

 function serialize(obj) {
  var str = [];
  for(var p in obj)
    if (obj.hasOwnProperty(p)) {
      str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
    }
  return str.join("&");
}
</script>
@stop

gobiglatest/resources/views/back/affiliation/part.blade.php
<div class="panel-heading2">
				@if(!empty($results))

				<table class="table">
					<thead>
						<tr>
							<th class="col-lg-1">Member Name</th>
						
							<th class="col-lg-1">Total Commission</th>
						</tr>
					</thead>
					<tbody>
					@foreach ($results as $result)
					
						<tr>
							@if($result->agentname != '')
							<td class="text-primary"><strong><a href="{!! route('user.show', [$result->agent_id]) !!}">{{ ucfirst($result->agentname) }}</a></strong></td>
						
							<td>{{ $result->totalamount }}</td>
							@endif
						</tr>
					@endforeach
					</tbody>
				</table>
				<div class="pull-right link">
				<?php echo $results->render(); ?>
			</div>
				@else
                <p style="text-align: center;">There is no data available.</p> 
				@endif	
			</div>

gobiglatest/resources/views/back/affiliation/referalfee.blade.php
@extends('back.template')
@section('head')
	<style type="text/css">
		.table { margin-bottom: 0; }
		.panel-heading { padding: 0 15px; }
	</style>
@stop
@section('main')
	<h1  class="page-header">Set Commission</h1>
	@if (Session::has('message'))
        <div class="alert alert-success">{{ Session::get('message') }}</div>
 	@endif
		<div class="panel">
			<div class="panel-heading1">
				@if($fees != '')
				<table class="table">
					<thead>
						<tr>
							<th class="col-lg-1">Type</th>
							<th class="col-lg-1">Monthly Commission</th>
							<th class="col-lg-1">Annual Commission</th>
							<th class="col-lg-1">Action</th>
						</tr>
					</thead>
					@foreach ($fees as $fee)
					<tbody>
						<tr>
							<td>{{ ucfirst($fee->type) }}</td>
							<td>{{ $fee->monthly_bonus }}</td>
							<td>{{ $fee->annual_bonus }}</td>
							<td><a href="{!! url('/editreferalfee', array('fee_id' => $fee->id)) !!}" class="btn btn-warning fa fa-pencil">Edit</a>&nbsp;
							<!--<a href="{!! url('/deletereferalfee', array('fees_id' => $fee->id)) !!}" class="btn btn-danger fa fa-trash" id="feedelete">Delete</a--></td>
						</tr>
					</tbody>
					@endforeach
				</table>	
				@else
				<p style="text-align: center;">There is no data available.<a href="{!! url('/showaddfee') !!}">Click here to set commission.</a></p>
				@endif
			</div>
		</div>
@stop
@section('scripts')
<script type="text/javascript">
$(document).ready(function(){
    $("#feedelete").click(function(e){
        if(!confirm('Are you sure to delete this?')){
            e.preventDefault();
            return false;
        }
        return true;
    });
});
</script>

@stop